services:

## --------------------------- SOL AI --------------------------- ##

  sol_landing_page:
    image: sol-landing-page:latest ## Nome da imagem gerada pelo build.sh
    networks:
      - nddNet ## Nome da rede interna

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.sol_landing.rule=Host(`sol.mairasoliani.com.br`)
        - traefik.http.routers.sol_landing.entrypoints=websecure
        - traefik.http.routers.sol_landing.priority=1
        - traefik.http.routers.sol_landing.tls.certresolver=letsencryptresolver
        - traefik.http.routers.sol_landing.service=sol_landing
        - traefik.http.services.sol_landing.loadbalancer.server.port=80
        - traefik.http.services.sol_landing.loadbalancer.passHostHeader=1

## --------------------------- SOL AI --------------------------- ##

networks:
  nddNet:
    external: true
    name: nddNet
