version: "3.7"

services:
  sol_landing_page:
    build:
      context: .
      dockerfile: Dockerfile
    image: sol-landing-page:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sol_landing.rule=Host(`sol.mairasoliani.com.br`)"
        - "traefik.http.routers.sol_landing.entrypoints=websecure"
        - "traefik.http.routers.sol_landing.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.sol_landing.loadbalancer.server.port=80"
        - "traefik.http.routers.sol_landing.service=sol_landing"
    networks:
      - nddNet

networks:
  nddNet:
    external: true
    name: nddNet
